spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show_sql: true
  cache:
    type: redis
    host: localhost
    port: 9090